volumes:
  pgdatasource:

services:
  test-db:
    image: postgres
    container_name: test_db
    restart: always
    environment:
      - DATABASE_HOST=127.0.0.1
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=docker
      - POSTGRES_PORT=5432
      - POSTGRES_DB=test
    ports:
      - "5432:5432"
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - pgdatasource:/var/lib/postgresql/data

  test-api:
    build: api/
    container_name: test-api
    # restart: always
    depends_on:
      test-db:
        condition: service_healthy
    ports:
      - "8080:8080"
    networks:
      - app-network
    environment:
      - NODE_ENV=development
      - DATABASE_HOST=test_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=docker
      - POSTGRES_PORT=5432
      - POSTGRES_DB=test
    # volumes:
    #   - type: bind
    #     source: ./api
    #     target: /api

  test-ui:
    build: ui/
    tty: true
    container_name: test-ui
    environment:
      - FAST_REFRESH=false
    depends_on:
      - "test-api"
    ports:
      - "3000:3000"
    networks:
      - app-network

    # Uncomment for hot reload
    volumes:
      - type: bind
        source: ./ui
        target: /app
      - /app/node_modules

networks:
  app-network:
    driver: bridge
